### PR TITLE
Add support to nnbd

### PR DESCRIPTION
**Pull request by canastro**
Add support to non-nullable by default.

Related with https://github.com/rodydavis/flutter_midi/issues/26 and https://github.com/rodydavis/flutter_midi/issues/27

### CODE REVIEW

**Comment by canastro** [comment]
I've just encountered this lib and I'm playing around with a small pet project. I'm having some dependencies conflicts and in this PR I try to address them. I'm super new with this lib (and dart/flutter in general), so let me know if you have any concerns that I might have missed here.

**Comment by MrHazee** [comment]
Nice @canastro! How can I use your branch correct? In my pubspec.yaml I´ve tried:
`flutter_midi:
    git: https://github.com/canastro/flutter_midi.git`
    
but that only gives me:

> Could not find a file named "pubspec.yaml"

Thanks

**Comment by canastro** [comment]
Theres an extra folder, try with: 

```
 git:
      url: https://github.com/canastro/flutter_midi.git
      path: flutter_midi/
```

**Comment by MrHazee** [comment]
Thank you, 
I tried what you suggested but got the same dependency problem as before:

> Because every version of flutter_midi from git depends on path_provider ^1.6.0 and abc2 depends on path_provider ^2.0.1, flutter_midi from git is forbidden.

> So, because abc2 depends on flutter_midi from git, version solving failed.
pub get failed (1; So, because abc2 depends on flutter_midi from git, version solving failed.)
exit code 1

I also tried
`git:
      url: https://github.com/canastro/flutter_midi.git
      path: flutter_midi/
      ref: nnbd`
      
and that gives me

> Error on line 17, column 11: Invalid description in the "flutter_midi" pubspec on the "flutter_midi_platform_interface" dependency: "../flutter_midi_platform_interface" is a relative path, but this isn't a local pubspec.
   ╷
17 │     path: ../flutter_midi_platform_interface
   │           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
pub get failed (65;    ╵)
exit code 65

Thanks

**Comment by canastro** [comment]
the last version you used should be the one. I changed the dependency of `flutter_midi_platform_interface` to use the one thats available in this same repo... I guess that doesnt play out well when using as dep in other projects :\

**Comment by MrHazee** [comment]
Ah got it. I should be able to modify the dependency of `flutter_midi_platform_interface` for my project then! 
Thanks a lot mate

**Comment by camillo777** [comment]
Hello, can someone point me to the correct yaml to use flutter_midi with Flutter 2?
I have tried the suggested but I still got the error:

```
flutter_midi: 
    git:
      url: https://github.com/canastro/flutter_midi.git
      path: flutter_midi/
      ref: nnbd
```

Error is:

> Error on line 17, column 11: Invalid description in the "flutter_midi" pubspec on the "flutter_midi_platform_interface" dependency: "../flutter_midi_platform_interface" is a relative path, but this isn't a local pubspec.
> 
>    ╷
> 17 │     path: ../flutter_midi_platform_interface
> 
> 
>    │           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>    ╵
> pub get failed (65;    ╵)
> exit code 65
>

**Comment by rodydavis** [comment]
I will work on merging this soon

**Review by rodydavis — APPROVED** [review]
LGTM

**Comment by canastro** [comment]
I think we'll still need [this one](https://github.com/osteele/dart-tonic/pull/8)  to be merged on dart-tonic to be fully nnbd.

**Comment by rodydavis** [comment]
Yeah for sure, I may need to create a fork.

**Pull request merged**
